### PR TITLE
add params to addons

### PR DESCRIPTION
**Pull request by remrem**
some updates to allow addons to have params...
https://github.com/timovn/blogotext/issues/70

### CODE REVIEW

**Comment by timovn** [comment]
Seems good, but are you sure you want to use the SQL database for the params? Isn’t using INI-files or text based data more appropriate?

I’d rather use SQL* only for the real data (articles, comments…) not the configuration info.

You could use a standard INI for a an addon, and in the add-on page, read it for params and add an equal amount of fields for the user to fill and then save it to the same file.

**Comment by remrem** [comment]
I could modify to use a file (.ini), but, I don't like the idea of use the same file for default settings and user settings, just in case of plugin update, user's preferences will be preserved whenever the plugin developper add new settings. I make some change and update this pull request ASAP ;)

**Comment by remrem** [comment]
So, I update the pull to move the SQL* to an .ini file.
The .ini will be 
`BT_ROOT.DIR_ADDONS.'/'.$addonName.'/params.ini'`
I keep the default settings in the declarative array of the plugins.
I also added the support for `<select>` for the params form.

**Comment by BoboTiG** [comment]
@remrem could you update these patches with a new up to day PR?

**Comment by remrem** [comment]
Ok, I will try to make a clean patch this week.

**Pull request closed without merging**
